"""initial schema

Revision ID: 20260731_0001
Revises:
Create Date: 2026-08-01 00:59:11.518419
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260731_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_type", sa.String(length=80), nullable=False),
        sa.Column("artifact_key", sa.String(length=280), nullable=False),
        sa.Column("current_version_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "case_id", "artifact_type", "artifact_key", name="uq_artifact_identity"
        ),
    )
    op.create_index(op.f("ix_artifacts_case_id"), "artifacts", ["case_id"], unique=False)
    op.create_table(
        "change_keys",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=280), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "key", name="uq_change_key_case_key"),
    )
    op.create_index(op.f("ix_change_keys_case_id"), "change_keys", ["case_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("added_at_revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "content_hash", name="uq_document_case_hash"),
    )
    op.create_index(op.f("ix_documents_case_id"), "documents", ["case_id"], unique=False)
    op.create_table(
        "recompute_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("target_revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claim_token", sa.String(length=36), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artifact_id", "target_revision", name="uq_job_artifact_revision"),
    )
    op.create_index(
        "ix_jobs_claim", "recompute_jobs", ["status", "lease_until", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_recompute_jobs_artifact_id"), "recompute_jobs", ["artifact_id"], unique=False
    )
    op.create_index(op.f("ix_recompute_jobs_case_id"), "recompute_jobs", ["case_id"], unique=False)
    op.create_table(
        "artifact_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("source_job_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("computed_at_revision", sa.Integer(), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("lineage", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_job_id"], ["recompute_jobs.id"], name="fk_artifact_version_source_job"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artifact_id", "version", name="uq_artifact_version"),
        sa.UniqueConstraint("source_job_id", name="uq_artifact_source_job"),
    )
    op.create_index(
        op.f("ix_artifact_versions_artifact_id"), "artifact_versions", ["artifact_id"], unique=False
    )
    with op.batch_alter_table("artifacts") as batch_op:
        batch_op.create_foreign_key(
            "fk_artifact_current_version",
            "artifact_versions",
            ["current_version_id"],
            ["id"],
            ondelete="SET NULL",
        )
    op.create_table(
        "assertions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("entity_id", sa.String(length=120), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("source_locator", sa.String(length=160), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("added_at_revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_assertion_timeline", "assertions", ["case_id", "entity_id", "occurred_at"], unique=False
    )
    op.create_index(op.f("ix_assertions_case_id"), "assertions", ["case_id"], unique=False)
    op.create_index(op.f("ix_assertions_document_id"), "assertions", ["document_id"], unique=False)
    op.create_table(
        "change_sets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("operation", sa.String(length=40), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("affected_keys", sa.JSON(), nullable=False),
        sa.Column("queued_artifact_ids", sa.JSON(), nullable=False),
        sa.Column("untouched_artifacts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "revision", name="uq_change_set_revision"),
    )
    op.create_index(op.f("ix_change_sets_case_id"), "change_sets", ["case_id"], unique=False)
    op.create_table(
        "document_retractions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("retracted_at_revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", name="uq_document_retraction"),
    )
    op.create_index(
        op.f("ix_document_retractions_case_id"), "document_retractions", ["case_id"], unique=False
    )
    op.create_table(
        "artifact_dependencies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("artifact_version_id", sa.String(length=36), nullable=False),
        sa.Column("change_key", sa.String(length=280), nullable=False),
        sa.Column("observed_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_version_id"], ["artifact_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artifact_version_id", "change_key", name="uq_artifact_dependency"),
    )
    op.create_index(
        op.f("ix_artifact_dependencies_artifact_version_id"),
        "artifact_dependencies",
        ["artifact_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifact_dependencies_change_key"),
        "artifact_dependencies",
        ["change_key"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artifact_dependencies_change_key"), table_name="artifact_dependencies")
    op.drop_index(
        op.f("ix_artifact_dependencies_artifact_version_id"), table_name="artifact_dependencies"
    )
    op.drop_table("artifact_dependencies")
    with op.batch_alter_table("artifacts") as batch_op:
        batch_op.drop_constraint("fk_artifact_current_version", type_="foreignkey")
    op.drop_index(op.f("ix_document_retractions_case_id"), table_name="document_retractions")
    op.drop_table("document_retractions")
    op.drop_index(op.f("ix_change_sets_case_id"), table_name="change_sets")
    op.drop_table("change_sets")
    op.drop_index(op.f("ix_assertions_document_id"), table_name="assertions")
    op.drop_index(op.f("ix_assertions_case_id"), table_name="assertions")
    op.drop_index("ix_assertion_timeline", table_name="assertions")
    op.drop_table("assertions")
    op.drop_index(op.f("ix_artifact_versions_artifact_id"), table_name="artifact_versions")
    op.drop_table("artifact_versions")
    op.drop_index(op.f("ix_recompute_jobs_case_id"), table_name="recompute_jobs")
    op.drop_index(op.f("ix_recompute_jobs_artifact_id"), table_name="recompute_jobs")
    op.drop_index("ix_jobs_claim", table_name="recompute_jobs")
    op.drop_table("recompute_jobs")
    op.drop_index(op.f("ix_documents_case_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_change_keys_case_id"), table_name="change_keys")
    op.drop_table("change_keys")
    op.drop_index(op.f("ix_artifacts_case_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_table("cases")
    # ### end Alembic commands ###
